export default {
    "map-world": [
        { "hc-key": "fo", "value": null }, { "hc-key": "um", "value": null }, { "hc-key": "us", "value": null }, { "hc-key": "jp", "value": null },
        { "hc-key": "sc", "value": null }, { "hc-key": "in", "value": null }, { "hc-key": "fr", "value": null }, { "hc-key": "fm", "value": null },
        { "hc-key": "cn", "value": null }, { "hc-key": "pt", "value": null }, { "hc-key": "sw", "value": null }, { "hc-key": "sh", "value": null },
        { "hc-key": "br", "value": null }, { "hc-key": "ki", "value": null }, { "hc-key": "ph", "value": null }, { "hc-key": "mx", "value": null },
        { "hc-key": "es", "value": null }, { "hc-key": "bu", "value": null }, { "hc-key": "mv", "value": null }, { "hc-key": "sp", "value": null },
        { "hc-key": "gb", "value": null }, { "hc-key": "gr", "value": null }, { "hc-key": "as", "value": null }, { "hc-key": "dk", "value": null },
        { "hc-key": "gl", "value": null }, { "hc-key": "gu", "value": null }, { "hc-key": "mp", "value": null }, { "hc-key": "pr", "value": null },
        { "hc-key": "vi", "value": null }, { "hc-key": "ca", "value": null }, { "hc-key": "st", "value": null }, { "hc-key": "cv", "value": null },
        { "hc-key": "dm", "value": null }, { "hc-key": "nl", "value": null }, { "hc-key": "jm", "value": null }, { "hc-key": "ws", "value": null },
        { "hc-key": "om", "value": null }, { "hc-key": "vc", "value": null }, { "hc-key": "tr", "value": null }, { "hc-key": "bd", "value": null },
        { "hc-key": "lc", "value": null }, { "hc-key": "nr", "value": null }, { "hc-key": "no", "value": null }, { "hc-key": "kn", "value": null },
        { "hc-key": "bh", "value": null }, { "hc-key": "to", "value": null }, { "hc-key": "fi", "value": null }, { "hc-key": "id", "value": null },
        { "hc-key": "mu", "value": null }, { "hc-key": "se", "value": null }, { "hc-key": "tt", "value": null }, { "hc-key": "my", "value": null },
        { "hc-key": "pa", "value": null }, { "hc-key": "pw", "value": null }, { "hc-key": "tv", "value": null }, { "hc-key": "mh", "value": null },
        { "hc-key": "cl", "value": null }, { "hc-key": "th", "value": null }, { "hc-key": "gd", "value": null }, { "hc-key": "ee", "value": null },
        { "hc-key": "ag", "value": null }, { "hc-key": "tw", "value": null }, { "hc-key": "bb", "value": null }, { "hc-key": "it", "value": null },
        { "hc-key": "mt", "value": null }, { "hc-key": "vu", "value": null }, { "hc-key": "sg", "value": null }, { "hc-key": "cy", "value": null },
        { "hc-key": "lk", "value": null }, { "hc-key": "km", "value": null }, { "hc-key": "fj", "value": null }, { "hc-key": "ru", "value": null },
        { "hc-key": "va", "value": null }, { "hc-key": "sm", "value": null }, { "hc-key": "kz", "value": null }, { "hc-key": "az", "value": null },
        { "hc-key": "tj", "value": null }, { "hc-key": "ls", "value": null }, { "hc-key": "uz", "value": null }, { "hc-key": "ma", "value": null },
        { "hc-key": "co", "value": null }, { "hc-key": "tl", "value": null }, { "hc-key": "tz", "value": null }, { "hc-key": "ar", "value": null },
        { "hc-key": "sa", "value": null }, { "hc-key": "pk", "value": null }, { "hc-key": "ye", "value": null }, { "hc-key": "ae", "value": null },
        { "hc-key": "ke", "value": null }, { "hc-key": "pe", "value": null }, { "hc-key": "do", "value": null }, { "hc-key": "ht", "value": null },
        { "hc-key": "pg", "value": null }, { "hc-key": "ao", "value": null }, { "hc-key": "kh", "value": null }, { "hc-key": "vn", "value": null },
        { "hc-key": "mz", "value": null }, { "hc-key": "cr", "value": null }, { "hc-key": "bj", "value": null }, { "hc-key": "ng", "value": null },
        { "hc-key": "ir", "value": null }, { "hc-key": "sv", "value": null }, { "hc-key": "sl", "value": null }, { "hc-key": "gw", "value": null },
        { "hc-key": "hr", "value": null }, { "hc-key": "bz", "value": null }, { "hc-key": "za", "value": null }, { "hc-key": "cf", "value": null },
        { "hc-key": "sd", "value": null }, { "hc-key": "cd", "value": null }, { "hc-key": "kw", "value": null }, { "hc-key": "de", "value": null },
        { "hc-key": "be", "value": null }, { "hc-key": "ie", "value": null }, { "hc-key": "kp", "value": null }, { "hc-key": "kr", "value": null },
        { "hc-key": "gy", "value": null }, { "hc-key": "hn", "value": null }, { "hc-key": "mm", "value": null }, { "hc-key": "ga", "value": null },
        { "hc-key": "gq", "value": null }, { "hc-key": "ni", "value": null }, { "hc-key": "lv", "value": null }, { "hc-key": "ug", "value": null },
        { "hc-key": "mw", "value": null }, { "hc-key": "am", "value": null }, { "hc-key": "sx", "value": null }, { "hc-key": "tm", "value": null },
        { "hc-key": "zm", "value": null }, { "hc-key": "nc", "value": null }, { "hc-key": "mr", "value": null }, { "hc-key": "dz", "value": null },
        { "hc-key": "lt", "value": null }, { "hc-key": "et", "value": null }, { "hc-key": "er", "value": null }, { "hc-key": "gh", "value": null },
        { "hc-key": "si", "value": null }, { "hc-key": "gt", "value": null }, { "hc-key": "ba", "value": null }, { "hc-key": "jo", "value": null },
        { "hc-key": "sy", "value": null }, { "hc-key": "mc", "value": null }, { "hc-key": "al", "value": null }, { "hc-key": "uy", "value": null },
        { "hc-key": "cnm", "value": null }, { "hc-key": "mn", "value": null }, { "hc-key": "rw", "value": null }, { "hc-key": "so", "value": null },
        { "hc-key": "bo", "value": null }, { "hc-key": "cm", "value": null }, { "hc-key": "cg", "value": null }, { "hc-key": "eh", "value": null },
        { "hc-key": "rs", "value": null }, { "hc-key": "me", "value": null }, { "hc-key": "tg", "value": null }, { "hc-key": "la", "value": null },
        { "hc-key": "af", "value": null }, { "hc-key": "ua", "value": null }, { "hc-key": "sk", "value": null }, { "hc-key": "jk", "value": null },
        { "hc-key": "bg", "value": null }, { "hc-key": "qa", "value": null }, { "hc-key": "li", "value": null }, { "hc-key": "at", "value": null },
        { "hc-key": "sz", "value": null }, { "hc-key": "hu", "value": null }, { "hc-key": "ro", "value": null }, { "hc-key": "ne", "value": null },
        { "hc-key": "lu", "value": null }, { "hc-key": "ad", "value": null }, { "hc-key": "ci", "value": null }, { "hc-key": "lr", "value": null },
        { "hc-key": "bn", "value": null }, { "hc-key": "iq", "value": null }, { "hc-key": "ge", "value": null }, { "hc-key": "gm", "value": null },
        { "hc-key": "ch", "value": null }, { "hc-key": "td", "value": null }, { "hc-key": "kv", "value": null }, { "hc-key": "lb", "value": null },
        { "hc-key": "dj", "value": null }, { "hc-key": "bi", "value": null }, { "hc-key": "sr", "value": null }, { "hc-key": "il", "value": null },
        { "hc-key": "ml", "value": null }, { "hc-key": "sn", "value": null }, { "hc-key": "gn", "value": null }, { "hc-key": "zw", "value": null },
        { "hc-key": "pl", "value": null }, { "hc-key": "mk", "value": null }, { "hc-key": "py", "value": null }, { "hc-key": "by", "value": null },
        { "hc-key": "cz", "value": null }, { "hc-key": "bf", "value": null }, { "hc-key": "na", "value": null }, { "hc-key": "ly", "value": null },
        { "hc-key": "tn", "value": null }, { "hc-key": "bt", "value": null }, { "hc-key": "md", "value": null }, { "hc-key": "ss", "value": null },
        { "hc-key": "bw", "value": null }, { "hc-key": "bs", "value": null }, { "hc-key": "nz", "value": null }, { "hc-key": "cu", "value": null },
        { "hc-key": "ec", "value": null }, { "hc-key": "au", "value": null }, { "hc-key": "ve", "value": null }, { "hc-key": "sb", "value": null },
        { "hc-key": "mg", "value": null }, { "hc-key": "is", "value": null }, { "hc-key": "eg", "value": null }, { "hc-key": "kg", "value": null },
        { "hc-key": "np", "value": null }
    ],
    "map-kz": [
        {"hc-key": "kz-5085", "value": null}, {"hc-key": "kz-qo", "value": null}, {"hc-key": "kz-ac", "value": null}, {"hc-key": "kz-as", "value": null},
        {"hc-key": "kz-qs", "value": null}, {"hc-key": "kz-nk", "value": null}, {"hc-key": "kz-pa", "value": null}, {"hc-key": "kz-am", "value": null},
        {"hc-key": "kz-zm", "value": null}, {"hc-key": "kz-ek", "value": null}, {"hc-key": "kz-ar", "value": null}, {"hc-key": "kz-mg", "value": null},
        {"hc-key": "kz-aa", "value": null}, {"hc-key": "kz-at", "value": null}, {"hc-key": "kz-wk", "value": null}, {"hc-key": "kz-sk", "value": null},
        {"hc-key": "kz-qg", "value": null}, {"hc-key": "kz-ab", "value": null}, {"hc-key": "kz-ji", "value": null},{"hc-key": "kz-aly", "value": null},
    ]
}